name: wave_generator
description: A dart package to generate audio wave data on the fly
version: 0.1.0
homepage: https://github.com/patchandthat/wave-generator

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.6.0
